trigger:
- none
pr:
- none

stages:
- stage: GoLive
  jobs:
  - job: GoLive
    displayName: move try.mudblazor.com to production slot
    steps:
    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'Azure-MudBlazor'
        WebAppName: 'trymudblazor'
        ResourceGroupName: 'MudBlazor'
        SourceSlot: staging