name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what you were doing when the bug occurred.
      placeholder: I was trying to...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: dropdown
    id: application-type
    attributes:
        label: What application type are you referring to?
        options:
          - Please select an application type...
          - ServerRendered
          - WebAssembly
          - MAUI
          - Other
    validations:
      required: true
  - type: input
    id: custom-application-type
    attributes:
      label: Custom Application Type
      description: If "Other" was selected above, please specify your application type here.
      placeholder: Specify your application type
    validations:
      required: false  # Only required if "Other" was selected above, but GitHub doesn't support such conditions yet.
  - type: input
    id: mudblazor-extension-version
    attributes:
      label: MudBlazor.Extension Version
      placeholder: Enter the version
    validations:
      required: true
  - type: input
    id: mudblazor-version
    attributes:
      label: MudBlazor Version
      placeholder: Enter the version
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser are you using?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other
    validations:
      required: true
  - type: textarea
    id: sample-solution
    attributes:
      label: Sample Solution
      description: If applicable, please provide a link to a sample solution or upload a project.
    validations:
      required: false
  - type: input
    id: pull-request
    attributes:
      label: Pull Request
      description: If you've already submitted a pull request that fixes this bug, or have a link to a fork please provide the link.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/fgilde/MudBlazor.Extensions/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
